export interface Channel {
  id: number;
  slug: string;
  name: string;
  category: 'Abertos' | 'Esportes' | 'Notícias' | 'Infantil' | 'Documentários' | 'Filmes e Séries' | 'Variedades' | 'Reality' | 'Adulto' | '24 Horas';
  source?: 'embedflix' | 'embedtv';
}

export const CHANNELS: Channel[] = [
  // Abertos
  { id: 1, slug: 'globosp', name: 'Globo SP', category: 'Abertos', source: 'embedtv' },
  { id: 2, slug: 'globorj', name: 'Globo RJ', category: 'Abertos', source: 'embedtv' },
  { id: 3, slug: 'globomg', name: 'Globo MG', category: 'Abertos', source: 'embedtv' },
  { id: 4, slug: 'sbtsp', name: 'SBT SP', category: 'Abertos', source: 'embedtv' },
  { id: 5, slug: 'recordsp', name: 'Record SP', category: 'Abertos', source: 'embedtv' },
  { id: 6, slug: 'bandsp', name: 'Band SP', category: 'Abertos', source: 'embedtv' },
  { id: 7, slug: 'rede-tv', name: 'Rede TV', category: 'Abertos', source: 'embedflix' },
  { id: 8, slug: 'cultura', name: 'Cultura', category: 'Abertos', source: 'embedtv' },
  { id: 101, slug: 'globoam', name: 'Globo AM', category: 'Abertos', source: 'embedtv' },
  { id: 102, slug: 'globoce', name: 'Globo CE', category: 'Abertos', source: 'embedtv' },
  { id: 103, slug: 'globoes', name: 'Globo ES', category: 'Abertos', source: 'embedtv' },
  { id: 104, slug: 'globopb', name: 'Globo PB', category: 'Abertos', source: 'embedtv' },
  { id: 105, slug: 'globope', name: 'Globo PE', category: 'Abertos', source: 'embedtv' },
  { id: 106, slug: 'globors', name: 'Globo RS', category: 'Abertos', source: 'embedtv' },
  { id: 107, slug: 'sbtrj', name: 'SBT RJ', category: 'Abertos', source: 'embedtv' },
  { id: 108, slug: 'recordrj', name: 'Record RJ', category: 'Abertos', source: 'embedtv' },
  { id: 109, slug: 'recordmg', name: 'Record MG', category: 'Abertos', source: 'embedtv' },
  { id: 110, slug: 'bandrj', name: 'Band RJ', category: 'Abertos', source: 'embedtv' },
  { id: 111, slug: 'aparecida', name: 'TV Aparecida', category: 'Abertos', source: 'embedtv' },
  { id: 112, slug: 'cancaonova', name: 'Canção Nova', category: 'Abertos', source: 'embedtv' },

  // Esportes
  { id: 9, slug: 'sportv', name: 'SporTV', category: 'Esportes', source: 'embedtv' },
  { id: 10, slug: 'sportv2', name: 'SporTV 2', category: 'Esportes', source: 'embedtv' },
  { id: 11, slug: 'sportv3', name: 'SporTV 3', category: 'Esportes', source: 'embedtv' },
  { id: 113, slug: 'sportv4', name: 'SporTV 4', category: 'Esportes', source: 'embedtv' },
  { id: 12, slug: 'espn', name: 'ESPN', category: 'Esportes', source: 'embedtv' },
  { id: 114, slug: 'espn2', name: 'ESPN 2', category: 'Esportes', source: 'embedtv' },
  { id: 115, slug: 'espn3', name: 'ESPN 3', category: 'Esportes', source: 'embedtv' },
  { id: 15, slug: 'espn4', name: 'ESPN 4', category: 'Esportes', source: 'embedtv' },
  { id: 116, slug: 'espn5', name: 'ESPN 5', category: 'Esportes', source: 'embedtv' },
  { id: 117, slug: 'espn6', name: 'ESPN 6', category: 'Esportes', source: 'embedtv' },
  { id: 18, slug: 'premiere', name: 'Premiere', category: 'Esportes', source: 'embedtv' },
  { id: 19, slug: 'premiere2', name: 'Premiere 2', category: 'Esportes', source: 'embedtv' },
  { id: 20, slug: 'premiere3', name: 'Premiere 3', category: 'Esportes', source: 'embedtv' },
  { id: 21, slug: 'premiere4', name: 'Premiere 4', category: 'Esportes', source: 'embedtv' },
  { id: 22, slug: 'premiere5', name: 'Premiere 5', category: 'Esportes', source: 'embedtv' },
  { id: 23, slug: 'premiere6', name: 'Premiere 6', category: 'Esportes', source: 'embedtv' },
  { id: 24, slug: 'premiere7', name: 'Premiere 7', category: 'Esportes', source: 'embedtv' },
  { id: 118, slug: 'premiere8', name: 'Premiere 8', category: 'Esportes', source: 'embedtv' },
  { id: 25, slug: 'bandsports', name: 'Band Sports', category: 'Esportes', source: 'embedtv' },
  { id: 26, slug: 'combate', name: 'Combate', category: 'Esportes', source: 'embedtv' },
  { id: 77, slug: 'ufcfightpass', name: 'UFC Fight Pass', category: 'Esportes', source: 'embedtv' },
  { id: 79, slug: 'caze1', name: 'Caze TV 1', category: 'Esportes', source: 'embedtv' },
  { id: 80, slug: 'caze2', name: 'Caze TV 2', category: 'Esportes', source: 'embedtv' },
  { id: 119, slug: 'caze3', name: 'Caze TV 3', category: 'Esportes', source: 'embedtv' },
  { id: 81, slug: 'primevideo', name: 'Prime Video 1', category: 'Esportes', source: 'embedtv' },
  { id: 82, slug: 'primevideo2', name: 'Prime Video 2', category: 'Esportes', source: 'embedtv' },
  { id: 120, slug: 'pt_sportv1', name: 'SporTV 1 PT', category: 'Esportes', source: 'embedtv' },
  { id: 121, slug: 'pt_sportv2', name: 'SporTV 2 PT', category: 'Esportes', source: 'embedtv' },
  { id: 122, slug: 'pt_sportv3', name: 'SporTV 3 PT', category: 'Esportes', source: 'embedtv' },
  { id: 123, slug: 'pt_sportv4', name: 'SporTV 4 PT', category: 'Esportes', source: 'embedtv' },
  { id: 124, slug: 'pt_sportv5', name: 'SporTV 5 PT', category: 'Esportes', source: 'embedtv' },
  { id: 125, slug: 'pt_sportv6', name: 'SporTV 6 PT', category: 'Esportes', source: 'embedtv' },
  { id: 126, slug: 'pt_sportv7', name: 'SporTV 7 PT', category: 'Esportes', source: 'embedtv' },
  { id: 127, slug: 'pt_abola', name: 'A Bola TV', category: 'Esportes', source: 'embedtv' },
  { id: 128, slug: 'pt_benficatv', name: 'Benfica TV', category: 'Esportes', source: 'embedtv' },
  { id: 129, slug: 'pt_canal11', name: 'Canal 11 PT', category: 'Esportes', source: 'embedtv' },
  { id: 130, slug: 'pt_eleven1', name: 'DAZN Eleven 1', category: 'Esportes', source: 'embedtv' },
  { id: 131, slug: 'pt_eleven2', name: 'DAZN Eleven 2', category: 'Esportes', source: 'embedtv' },
  { id: 132, slug: 'pt_eleven3', name: 'DAZN Eleven 3', category: 'Esportes', source: 'embedtv' },
  { id: 95, slug: 'xsports', name: 'XSports', category: 'Esportes', source: 'embedtv' },

  // Filmes e Séries
  { id: 44, slug: 'telecine-action', name: 'Telecine Action', category: 'Filmes e Séries', source: 'embedflix' },
  { id: 45, slug: 'telecine-premium', name: 'Telecine Premium', category: 'Filmes e Séries', source: 'embedflix' },
  { id: 46, slug: 'telecine-pipoca', name: 'Telecine Pipoca', category: 'Filmes e Séries', source: 'embedflix' },
  { id: 47, slug: 'telecine-fun', name: 'Telecine Fun', category: 'Filmes e Séries', source: 'embedflix' },
  { id: 48, slug: 'telecine-touch', name: 'Telecine Touch', category: 'Filmes e Séries', source: 'embedflix' },
  { id: 49, slug: 'telecine-cult', name: 'Telecine Cult', category: 'Filmes e Séries', source: 'embedflix' },
  { id: 50, slug: 'hbo', name: 'HBO', category: 'Filmes e Séries', source: 'embedflix' },
  { id: 51, slug: 'hbo-2', name: 'HBO 2', category: 'Filmes e Séries', source: 'embedflix' },
  { id: 52, slug: 'hbo-plus', name: 'HBO Plus', category: 'Filmes e Séries', source: 'embedflix' },
  { id: 53, slug: 'hbo-family', name: 'HBO Family', category: 'Filmes e Séries', source: 'embedflix' },
  { id: 54, slug: 'max-prime', name: 'Max Prime', category: 'Filmes e Séries', source: 'embedflix' },
  { id: 55, slug: 'max-up', name: 'Max Up', category: 'Filmes e Séries', source: 'embedflix' },
  { id: 56, slug: 'cinemax', name: 'Cinemax', category: 'Filmes e Séries', source: 'embedflix' },
  { id: 57, slug: 'megapix', name: 'Megapix', category: 'Filmes e Séries', source: 'embedflix' },
  { id: 58, slug: 'fx', name: 'FX', category: 'Filmes e Séries', source: 'embedflix' },
  { id: 59, slug: 'fox', name: 'Fox', category: 'Filmes e Séries', source: 'embedflix' },
  { id: 60, slug: 'sony-channel', name: 'Sony Channel', category: 'Filmes e Séries', source: 'embedflix' },
  { id: 61, slug: 'warner-channel', name: 'Warner Channel', category: 'Filmes e Séries', source: 'embedflix' },
  { id: 62, slug: 'universal-channel', name: 'Universal Channel', category: 'Filmes e Séries', source: 'embedflix' },
  { id: 63, slug: 'axn', name: 'AXN', category: 'Filmes e Séries', source: 'embedflix' },
  { id: 64, slug: 'tnt', name: 'TNT', category: 'Filmes e Séries', source: 'embedflix' },
  { id: 65, slug: 'space', name: 'Space', category: 'Filmes e Séries', source: 'embedflix' },
  { id: 69, slug: 'paramount-network', name: 'Paramount Network', category: 'Filmes e Séries', source: 'embedflix' },
  { id: 133, slug: 'disneyplus1', name: 'Disney Plus 1', category: 'Filmes e Séries', source: 'embedtv' },
  { id: 134, slug: 'disneyplus2', name: 'Disney Plus 2', category: 'Filmes e Séries', source: 'embedtv' },
  { id: 135, slug: 'disneyplus3', name: 'Disney Plus 3', category: 'Filmes e Séries', source: 'embedtv' },
  { id: 136, slug: 'netflix1', name: 'Netflix 1', category: 'Filmes e Séries', source: 'embedtv' },
  { id: 137, slug: 'netflix2', name: 'Netflix 2', category: 'Filmes e Séries', source: 'embedtv' },
  { id: 138, slug: 'netflix3', name: 'Netflix 3', category: 'Filmes e Séries', source: 'embedtv' },
  { id: 139, slug: 'starplus1', name: 'Star Plus 1', category: 'Filmes e Séries', source: 'embedtv' },
  { id: 140, slug: 'starplus2', name: 'Star Plus 2', category: 'Filmes e Séries', source: 'embedtv' },
  { id: 141, slug: 'starplus3', name: 'Star Plus 3', category: 'Filmes e Séries', source: 'embedtv' },

  // Infantil
  { id: 34, slug: 'cartoon-network', name: 'Cartoon Network', category: 'Infantil', source: 'embedflix' },
  { id: 35, slug: 'disney-channel', name: 'Disney Channel', category: 'Infantil', source: 'embedflix' },
  { id: 36, slug: 'disney-junior', name: 'Disney Junior', category: 'Infantil', source: 'embedflix' },
  { id: 37, slug: 'nickelodeon', name: 'Nickelodeon', category: 'Infantil', source: 'embedflix' },
  { id: 38, slug: 'nick-jr', name: 'Nick Jr', category: 'Infantil', source: 'embedflix' },
  { id: 40, slug: 'discovery-kids', name: 'Discovery Kids', category: 'Infantil', source: 'embedflix' },
  { id: 142, slug: 'gloob', name: 'Gloob', category: 'Infantil', source: 'embedtv' },
  { id: 143, slug: 'gloobinho', name: 'Gloobinho', category: 'Infantil', source: 'embedtv' },
  { id: 144, slug: 'tooncito', name: 'Tooncito', category: 'Infantil', source: 'embedtv' },

  // Documentários
  { id: 39, slug: 'discovery-channel', name: 'Discovery Channel', category: 'Documentários', source: 'embedflix' },
  { id: 41, slug: 'animal-planet', name: 'Animal Planet', category: 'Documentários', source: 'embedflix' },
  { id: 42, slug: 'history-channel', name: 'History Channel', category: 'Documentários', source: 'embedflix' },
  { id: 43, slug: 'national-geographic', name: 'National Geographic', category: 'Documentários', source: 'embedflix' },
  { id: 75, slug: 'investigation-discovery', name: 'Investigation Discovery', category: 'Documentários', source: 'embedflix' },
  { id: 76, slug: 'travel-channel', name: 'Travel Channel', category: 'Documentários', source: 'embedflix' },
  { id: 145, slug: 'discovery-turbo', name: 'Discovery Turbo', category: 'Documentários', source: 'embedtv' },
  { id: 146, slug: 'discovery-science', name: 'Discovery Science', category: 'Documentários', source: 'embedtv' },
  { id: 147, slug: 'discovery-world', name: 'Discovery World', category: 'Documentários', source: 'embedtv' },
  { id: 148, slug: 'natgeo-wild', name: 'NatGeo Wild', category: 'Documentários', source: 'embedtv' },
  { id: 149, slug: 'history-2', name: 'History 2', category: 'Documentários', source: 'embedtv' },

  // Notícias
  { id: 29, slug: 'cnn-brasil', name: 'CNN Brasil', category: 'Notícias', source: 'embedflix' },
  { id: 30, slug: 'globo-news', name: 'Globo News', category: 'Notícias', source: 'embedflix' },
  { id: 31, slug: 'band-news', name: 'Band News', category: 'Notícias', source: 'embedflix' },
  { id: 32, slug: 'record-news', name: 'Record News', category: 'Notícias', source: 'embedflix' },
  { id: 33, slug: 'sbt-news', name: 'SBT News', category: 'Notícias', source: 'embedflix' },
  { id: 150, slug: 'jovempannews', name: 'Jovem Pan News', category: 'Notícias', source: 'embedtv' },
  { id: 151, slug: 'pt_rtp1', name: 'RTP 1 PT', category: 'Notícias', source: 'embedtv' },
  { id: 152, slug: 'pt_rtp2', name: 'RTP 2 PT', category: 'Notícias', source: 'embedtv' },
  { id: 153, slug: 'pt_sic', name: 'SIC PT', category: 'Notícias', source: 'embedtv' },
  { id: 154, slug: 'pt_tvi', name: 'TVI PT', category: 'Notícias', source: 'embedtv' },

  // Variedades
  { id: 28, slug: 'fish-tv', name: 'Fish TV', category: 'Variedades', source: 'embedflix' },
  { id: 66, slug: 'mtv', name: 'MTV', category: 'Variedades', source: 'embedflix' },
  { id: 67, slug: 'multishow', name: 'Multishow', category: 'Variedades', source: 'embedflix' },
  { id: 68, slug: 'comedy-central', name: 'Comedy Central', category: 'Variedades', source: 'embedflix' },
  { id: 70, slug: 'e-entertainment', name: 'E! Entertainment', category: 'Variedades', source: 'embedflix' },
  { id: 71, slug: 'lifetime', name: 'Lifetime', category: 'Variedades', source: 'embedflix' },
  { id: 72, slug: 'tlc', name: 'TLC', category: 'Variedades', source: 'embedflix' },
  { id: 73, slug: 'food-network', name: 'Food Network', category: 'Variedades', source: 'embedflix' },
  { id: 74, slug: 'hgtv', name: 'HGTV', category: 'Variedades', source: 'embedflix' },
  { id: 88, slug: 'getv', name: 'GETV', category: 'Variedades', source: 'embedflix' },
  { id: 155, slug: 'gnt', name: 'GNT', category: 'Variedades', source: 'embedtv' },
  { id: 156, slug: 'viva', name: 'Viva', category: 'Variedades', source: 'embedtv' },

  // Reality
  { id: 89, slug: 'bbb1', name: 'BBB 1', category: 'Reality', source: 'embedtv' },
  { id: 90, slug: 'bbb2', name: 'BBB 2', category: 'Reality', source: 'embedtv' },
  { id: 91, slug: 'bbb3', name: 'BBB 3', category: 'Reality', source: 'embedtv' },
  { id: 92, slug: 'bbb4', name: 'BBB 4', category: 'Reality', source: 'embedtv' },
  { id: 93, slug: 'bbb5', name: 'BBB 5', category: 'Reality', source: 'embedtv' },
  { id: 94, slug: 'bbb6', name: 'BBB 6', category: 'Reality', source: 'embedtv' },
  { id: 157, slug: 'bbb7', name: 'BBB 7', category: 'Reality', source: 'embedtv' },
  { id: 158, slug: 'bbb8', name: 'BBB 8', category: 'Reality', source: 'embedtv' },
  { id: 159, slug: 'bbb9', name: 'BBB 9', category: 'Reality', source: 'embedtv' },
  { id: 160, slug: 'bbbmosaico', name: 'BBB Mosaico', category: 'Reality', source: 'embedtv' },
  { id: 161, slug: 'afazenda', name: 'A Fazenda', category: 'Reality', source: 'embedtv' },

  // 24 Horas
  { id: 162, slug: 'chaves', name: 'Chaves 24h', category: '24 Horas', source: 'embedtv' },
  { id: 163, slug: 'chapolin', name: 'Chapolin 24h', category: '24 Horas', source: 'embedtv' },
  { id: 164, slug: 'simpsons', name: 'Simpsons 24h', category: '24 Horas', source: 'embedtv' },
  { id: 165, slug: 'todomundoodeiaochris', name: 'Chris 24h', category: '24 Horas', source: 'embedtv' },
  { id: 166, slug: 'euapatroaecriancas', name: 'Patroa 24h', category: '24 Horas', source: 'embedtv' },

  // Adulto
  { id: 167, slug: 'sexyhot', name: 'Sexy Hot', category: 'Adulto', source: 'embedtv' },
  { id: 168, slug: 'playboytv', name: 'Playboy TV', category: 'Adulto', source: 'embedtv' },
  { id: 169, slug: 'venus', name: 'Venus', category: 'Adulto', source: 'embedtv' },
  { id: 170, slug: 'sextreme', name: 'Sextreme', category: 'Adulto', source: 'embedtv' },
  { id: 171, slug: 'penthouse', name: 'Penthouse', category: 'Adulto', source: 'embedtv' },
  { id: 172, slug: 'brasileirinhas', name: 'Brasileirinhas', category: 'Adulto', source: 'embedtv' },
];
