export interface Channel {
  id: number;
  slug: string;
  name: string;
  category: 'Abertos' | 'Esportes' | 'Notícias' | 'Infantil' | 'Documentários' | 'Filmes e Séries' | 'Variedades' | 'Reality';
}

export const CHANNELS: Channel[] = [
  { id: 1, slug: 'globo-sp', name: 'Globo SP', category: 'Abertos' },
  { id: 2, slug: 'globo-rj', name: 'Globo RJ', category: 'Abertos' },
  { id: 3, slug: 'globo-mg', name: 'Globo MG', category: 'Abertos' },
  { id: 4, slug: 'sbt', name: 'SBT', category: 'Abertos' },
  { id: 5, slug: 'record-tv', name: 'Record TV', category: 'Abertos' },
  { id: 6, slug: 'band', name: 'Band', category: 'Abertos' },
  { id: 7, slug: 'rede-tv', name: 'Rede TV', category: 'Abertos' },
  { id: 8, slug: 'cultura', name: 'Cultura', category: 'Abertos' },
  { id: 9, slug: 'sportv', name: 'SporTV', category: 'Esportes' },
  { id: 10, slug: 'sportv-2', name: 'SporTV 2', category: 'Esportes' },
  { id: 11, slug: 'sportv-3', name: 'SporTV 3', category: 'Esportes' },
  { id: 12, slug: 'espn', name: 'ESPN', category: 'Esportes' },
  { id: 13, slug: 'espn-2', name: 'ESPN 2', category: 'Esportes' },
  { id: 14, slug: 'espn-3', name: 'ESPN 3', category: 'Esportes' },
  { id: 15, slug: 'espn-4', name: 'ESPN 4', category: 'Esportes' },
  { id: 16, slug: 'fox-sports', name: 'Fox Sports', category: 'Esportes' },
  { id: 17, slug: 'fox-sports-2', name: 'Fox Sports 2', category: 'Esportes' },
  { id: 18, slug: 'premiere', name: 'Premiere', category: 'Esportes' },
  { id: 19, slug: 'premiere-2', name: 'Premiere 2', category: 'Esportes' },
  { id: 20, slug: 'premiere-3', name: 'Premiere 3', category: 'Esportes' },
  { id: 21, slug: 'premiere-4', name: 'Premiere 4', category: 'Esportes' },
  { id: 22, slug: 'premiere-5', name: 'Premiere 5', category: 'Esportes' },
  { id: 23, slug: 'premiere-6', name: 'Premiere 6', category: 'Esportes' },
  { id: 24, slug: 'premiere-7', name: 'Premiere 7', category: 'Esportes' },
  { id: 25, slug: 'band-sports', name: 'Band Sports', category: 'Esportes' },
  { id: 26, slug: 'combate', name: 'Combate', category: 'Esportes' },
  { id: 27, slug: 'ei-plus', name: 'EI Plus', category: 'Esportes' },
  { id: 28, slug: 'fish-tv', name: 'Fish TV', category: 'Variedades' },
  { id: 29, slug: 'cnn-brasil', name: 'CNN Brasil', category: 'Notícias' },
  { id: 30, slug: 'globo-news', name: 'Globo News', category: 'Notícias' },
  { id: 31, slug: 'band-news', name: 'Band News', category: 'Notícias' },
  { id: 32, slug: 'record-news', name: 'Record News', category: 'Notícias' },
  { id: 33, slug: 'sbt-news', name: 'SBT News', category: 'Notícias' },
  { id: 34, slug: 'cartoon-network', name: 'Cartoon Network', category: 'Infantil' },
  { id: 35, slug: 'disney-channel', name: 'Disney Channel', category: 'Infantil' },
  { id: 36, slug: 'disney-junior', name: 'Disney Junior', category: 'Infantil' },
  { id: 37, slug: 'nickelodeon', name: 'Nickelodeon', category: 'Infantil' },
  { id: 38, slug: 'nick-jr', name: 'Nick Jr', category: 'Infantil' },
  { id: 39, slug: 'discovery-channel', name: 'Discovery Channel', category: 'Documentários' },
  { id: 40, slug: 'discovery-kids', name: 'Discovery Kids', category: 'Infantil' },
  { id: 41, slug: 'animal-planet', name: 'Animal Planet', category: 'Documentários' },
  { id: 42, slug: 'history-channel', name: 'History Channel', category: 'Documentários' },
  { id: 43, slug: 'national-geographic', name: 'National Geographic', category: 'Documentários' },
  { id: 44, slug: 'telecine-action', name: 'Telecine Action', category: 'Filmes e Séries' },
  { id: 45, slug: 'telecine-premium', name: 'Telecine Premium', category: 'Filmes e Séries' },
  { id: 46, slug: 'telecine-pipoca', name: 'Telecine Pipoca', category: 'Filmes e Séries' },
  { id: 47, slug: 'telecine-fun', name: 'Telecine Fun', category: 'Filmes e Séries' },
  { id: 48, slug: 'telecine-touch', name: 'Telecine Touch', category: 'Filmes e Séries' },
  { id: 49, slug: 'telecine-cult', name: 'Telecine Cult', category: 'Filmes e Séries' },
  { id: 50, slug: 'hbo', name: 'HBO', category: 'Filmes e Séries' },
  { id: 51, slug: 'hbo-2', name: 'HBO 2', category: 'Filmes e Séries' },
  { id: 52, slug: 'hbo-plus', name: 'HBO Plus', category: 'Filmes e Séries' },
  { id: 53, slug: 'hbo-family', name: 'HBO Family', category: 'Filmes e Séries' },
  { id: 54, slug: 'max-prime', name: 'Max Prime', category: 'Filmes e Séries' },
  { id: 55, slug: 'max-up', name: 'Max Up', category: 'Filmes e Séries' },
  { id: 56, slug: 'cinemax', name: 'Cinemax', category: 'Filmes e Séries' },
  { id: 57, slug: 'megapix', name: 'Megapix', category: 'Filmes e Séries' },
  { id: 58, slug: 'fx', name: 'FX', category: 'Filmes e Séries' },
  { id: 59, slug: 'fox', name: 'Fox', category: 'Filmes e Séries' },
  { id: 60, slug: 'sony-channel', name: 'Sony Channel', category: 'Filmes e Séries' },
  { id: 61, slug: 'warner-channel', name: 'Warner Channel', category: 'Filmes e Séries' },
  { id: 62, slug: 'universal-channel', name: 'Universal Channel', category: 'Filmes e Séries' },
  { id: 63, slug: 'axn', name: 'AXN', category: 'Filmes e Séries' },
  { id: 64, slug: 'tnt', name: 'TNT', category: 'Filmes e Séries' },
  { id: 65, slug: 'space', name: 'Space', category: 'Filmes e Séries' },
  { id: 66, slug: 'mtv', name: 'MTV', category: 'Variedades' },
  { id: 67, slug: 'multishow', name: 'Multishow', category: 'Variedades' },
  { id: 68, slug: 'comedy-central', name: 'Comedy Central', category: 'Variedades' },
  { id: 69, slug: 'paramount-network', name: 'Paramount Network', category: 'Filmes e Séries' },
  { id: 70, slug: 'e-entertainment', name: 'E! Entertainment', category: 'Variedades' },
  { id: 71, slug: 'lifetime', name: 'Lifetime', category: 'Variedades' },
  { id: 72, slug: 'tlc', name: 'TLC', category: 'Variedades' },
  { id: 73, slug: 'food-network', name: 'Food Network', category: 'Variedades' },
  { id: 74, slug: 'hgtv', name: 'HGTV', category: 'Variedades' },
  { id: 75, slug: 'investigation-discovery', name: 'Investigation Discovery', category: 'Documentários' },
  { id: 76, slug: 'travel-channel', name: 'Travel Channel', category: 'Documentários' },
  { id: 77, slug: 'ufc-fight-pass', name: 'UFC Fight Pass', category: 'Esportes' },
  { id: 79, slug: 'caze-tv-1', name: 'Caze TV 1', category: 'Esportes' },
  { id: 80, slug: 'caze-tv-2', name: 'Caze TV 2', category: 'Esportes' },
  { id: 81, slug: 'prime-video-1', name: 'Prime Video 1', category: 'Esportes' },
  { id: 82, slug: 'prime-video-2', name: 'Prime Video 2', category: 'Esportes' },
  { id: 83, slug: 'prime-video-3', name: 'Prime Video 3', category: 'Esportes' },
  { id: 84, slug: 'paramount-1', name: 'Paramount 1', category: 'Esportes' },
  { id: 85, slug: 'paramount-2', name: 'Paramount 2', category: 'Esportes' },
  { id: 86, slug: 'paramount-3', name: 'Paramount 3', category: 'Esportes' },
  { id: 87, slug: 'tnt-custom', name: 'TNT Custom', category: 'Esportes' },
  { id: 88, slug: 'getv', name: 'GETV', category: 'Variedades' },
  { id: 89, slug: 'bbb1', name: 'BBB 1', category: 'Reality' },
  { id: 90, slug: 'bbb2', name: 'BBB 2', category: 'Reality' },
  { id: 91, slug: 'bbb3', name: 'BBB 3', category: 'Reality' },
  { id: 92, slug: 'bbb4', name: 'BBB 4', category: 'Reality' },
  { id: 93, slug: 'bbb5', name: 'BBB 5', category: 'Reality' },
  { id: 94, slug: 'bbb6', name: 'BBB 6', category: 'Reality' },
  { id: 95, slug: 'xsports', name: 'XSports', category: 'Esportes' },
];
